name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: setup
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test
