name: CD

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config --global user.email "frontend@securityscorecard.io"
          git config --global user.name "frontend"

      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Build Packages
        run: yarn lerna run build

      - name: Publish package
        run: |
          yarn logout
          npm config set '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}'
          yarn lerna publish from-package --yes --no-verify-access
