name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Packages
        run: yarn lerna run build

      - name: Publish package
        run: yarn lerna publish --yes --message 'chore: release new versions'
