name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: Configure CI Git User
        run: |
          git config --global user.email "frontend+npmbot@securityscorecard.io"
          git config --global user.name "ci@$GITHUB_ACTOR"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: yarn install

      - name: Build Packages
        run: yarn lerna run build

      - name: Publish package
        run: yarn lerna publish --yes --message 'chore: release new versions'
